#!/bin/bash
# Bash arrays https://opensource.com/article/18/5/you-dont-know-bash-intro-bash-arrays
# Bash Integer context https://linuxize.com/post/bash-increment-decrement-variable/ 

# Input file
input="input.txt"
